apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
  namespace: huellitas
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "huellitas_root_2024"
  MYSQL_DATABASE: "huellitas_db"
  MYSQL_USER: "huellitas_user"
  MYSQL_PASSWORD: "huellitas_pass_2024"
